#!/usr/bin/with-contenv bash

cd /app/duplicati || exit

 exec \
	s6-setuidgid abc mono Duplicati.Server.exe \
	--webservice-interface=any --webservice-allowed-hostnames=* --server-datafolder=/config
